### ISSUE TITLE
distribution_focal_loss is simply CE?

### ISSUE THREAD

**Issue by qianyizhang** [implus/GFocal#1]
https://github.com/implus/GFocal/blob/master/mmdet/models/losses/gfocal_loss.py#L42-L46
`

    disl = label.long()
    disr = disl + 1

    wl = disr.float() - label # this is (label.long() + 1).float() - label , which is simply 1.0
    wr = label - disl.float() # this is label - label.long().float(), which is 0.0
`
therefore, your GFL is simply CE?

**Comment by implus** [comment]
Hi, note that label is a float vector, so it's not simply 1.0 or 0.0. You can check the runtime values by yourself.

Thanks!
