### ISSUE TITLE
如何快速使用GFL

### ISSUE THREAD

**Issue by zjp99** [implus/GFocal#2]
我目前使用的是focal loss，如何更改能直接使用您提出的GFL,来进行实验？

**Comment by implus** [comment]
Please refer to the related code in:

https://github.com/implus/GFocal/blob/master/mmdet/models/losses/gfocal_loss.py
https://github.com/implus/GFocal/blob/master/mmdet/models/anchor_heads/gfl_head.py
https://github.com/implus/GFocal/blob/master/configs/gfl_r50_1x.py

Thanks!
