### ISSUE TITLE
Model weights in https://github.com/open-mmlab/mmdetection/blob/master/configs/gfl/README.md

### ISSUE THREAD

**Issue by QuantScientist** [implus/GFocal#6]
Hello,
I tried the link on Mmdetection however not only the names of the config files are different but also the Links to the weights are dead.
For instance:
https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/gfl/gfl_x101_32x4d_fpn_mstrain_2x_coco/gfl_x101_32x4d_fpn_mstrain_2x_coco_20200630_102002-50c1ffdb.pth

**Comment by implus** [comment]
Hi, I donot have the access to amazonaws of mmdetection. The upload is done by several major contributors. Maybe you can raise this issue directly in the MMdetection official repo. Thanks a lot~

**Comment by QuantScientist** [comment]
I am trying your version now thanks.
