### ISSUE TITLE
Difference from the APs of FCOS and ATSS from mmdetection

### ISSUE THREAD

**Issue by youngwanLEE** [implus/GFocal#8]
Hi,

I'm very impressed by your excellent work.

When I read and compared your experiments about FCOS and ATSS, I was confused by those values you mentioned in Table 2 (a).

|       | FCOS | ATSS |
|-------|------|------|
| mmdet | [38.6](https://github.com/open-mmlab/mmdetection/tree/master/configs/fcos#results-and-models) | [39.4](https://github.com/open-mmlab/mmdetection/tree/master/configs/atss#results-and-models) |
| yours(Dirac delta) | 38.5 | 39.2 |

Could you explain what I missed?

Thanks

**Comment by implus** [comment]
Hi, a difference around ~0.1 AP is mainly the randomness fact (e.g., different initialization seeds).  For example, the performance of GFL_r50_1x is usually 40.2, but sometimes you can get 40.3.

**Comment by implus** [comment]
And for an apple-to-apple fair comparison in ablation study, we run all experiments instead of just copying the results from other papers or repos.
